version: '3'
services:
  server1:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment: &environment
      - DESIRED_RATE_TX=50
      - AMOUNT_DATA_BYTES=0
      - TEST_TIME_MINUTES=1
      - RPC_URL=http://localhost:1234  #http://35.239.2.191:4545
    network_mode: host #using localhost instead of isolated network

  server2:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment: *environment
    network_mode: host